{
 "title": "LAN RTT",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency Groupings  - Across all  Customer TCP Flows",
   "type": "heatmap",
   "description": "latency groupings across all flows",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(lanRtt_flows_histo_value_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Mean - Across all  Customer TCP Flows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "lanRtt_mean_value", "legendFormat": "Latency" }
   ]
  },
  {
   "title": "Mean Latency  - Aggregated per unique device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "lanRtt_aggregated_device_flows_mean_value{}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Latency Groupings - Aggregated per unique device",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(lanRtt_aggregated_device_flows_histo_value_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Unique Device Count",
   "type": "timeseries",
   "description": "Unique Devices establishing TCP connections during each sampling period",
   "gridPos": { "h": 18, "w": 14, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "lanRtt_unique_device_flows_value{}",
     "legendFormat": "Unique Device Count"
    }
   ]
  }
 ]
}